Repository nanoframework/nanoFramework.Logging, pull requests merged in 2021-05, with the labels that each got.

#7 Changed nfproj to sign the assembly
  nanoFramework.Logging/nanoFramework.Logging.nfproj
Labels: Area: Config-and-Build

#10 Change Debug.WriteLine to Console.WriteLine
  nanoFramework.Logging/DebugLogger.cs
Labels: Type: bug

#28 Migrating to System.IO.Ports
  README.md
  Tests/UnitTestDebugLogging/SerialTest.cs
  Tests/UnitTestDebugLogging/UnitTestDebugLogging.nfproj
  Tests/UnitTestDebugLogging/packages.config
  nanoFramework.Logging.Serial/SerialLogger.cs
  nanoFramework.Logging.Serial/SerialLoggerFactory.cs
  nanoFramework.Logging.Serial/nanoFramework.Logging.Serial.nfproj
  nanoFramework.Logging.Serial/packages.config
Labels: Type: Unit Tests, Type: dependencies, Type: enhancement

#31 Fixing nuget reference for Logging.Serial
  nanoFramework.Logging.Serial.nuspec
Labels: Type: bug
